### ISSUE TITLE
Do not handle Guzzle exception

### ISSUE THREAD

**Issue by DanMan** [repat/plentymarkets-rest-client#13]
https://github.com/repat/plentymarkets-rest-client/blob/f6672296688024de645d8195366470bbdc21f015/src/PlentymarketsRestClient/PlentymarketsRestClient.php#L78-L83

I'd prefer to catch that exception myself so I can have some insight into what the error was. A simple `false` return really doesn't cut it.

**Comment by repat** [comment]
Sorry I totally missed this in May, will provide a fix asap

**Comment by repat** [comment]
@DanMan check out [version 0.1.10](https://github.com/repat/plentymarkets-rest-client/releases/tag/0.1.10) and https://github.com/repat/plentymarkets-rest-client/commit/515bff2ca96df03e42fe98a0e7762d7d11c5dbdc
