### ISSUE TITLE
Request parameters not working

### ISSUE THREAD

**Issue by c-zehnter** [repat/plentymarkets-rest-client#3]
Hi, thanks for providing the client!
I'm facing a problem using the request parameters `page` and `itemsPerPage` and thought you might have an idea why it's not working properly.

I'm using a simple `$client->get()` call with `$path = "/rest/orders";` to fetch the latest orders. The result is a paginated response with 50 entries per page, just as described in the developer's guide. According to the plentymarkets forum, it should be possible to increase the number by specifying the `itemsPerPage` parameter. However, if I add the parameter to the `$path` variable like this: 
`$path = "/rest/orders?itemsPerPage=200";`
the response doesn't change at all. Using the `page` parameter to get anything but the first page doesn't work for me either. I also tried to use a number <50 which also doesn't work. Any idea why this does not work? Am I missing something? Thanks for your help!

**Comment by lkreimann** [comment]
You shouldn't add the parameters to the path, instead put them in the `$parameterArray` as specified in the [README](https://github.com/repat/plentymarkets-rest-client/blob/master/README.md).

**Comment by repat** [comment]
Please use `$client->get($path, $parameterArray);` with `$parameterArray` like so:
```php
$parameterArray = [
    "itemsPerPage" => "20"
];
```
