### ISSUE TITLE
Possible to update guzzlehttp to 6.3.3 - the current Build is PHP 7.2 incompatible

### ISSUE THREAD

**Issue by x360andy** [repat/plentymarkets-rest-client#4]
Warning:  count(): Parameter must be an array or an object that implements Countable in <b>C:\....\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php</b> on line <b>67</b>

https://packagist.org/packages/guzzlehttp/guzzle

Thank you!

**Comment by repat** [comment]
I changed the composer.json, that should work. Don't work for the company I developed this for anymore and don't have time to test it but you're welcome to :)

**Comment by repat** [comment]
@pquerner this should be relevant for you too then. Could you check if `0.1.1` fixed it?

**Comment by pquerner** [comment]
@repat Yep, that fixed it. However, same issue applies here I had with the "carbon" dependency. You force 2 specific versions as a hard dependency. Thats never a good idea.

**Comment by repat** [comment]
Huh, that's true. Not the slightest idea why I did that. Anyway, I changed it to `^6.2.2`. Lmk how it goes

**Comment by repat** [comment]
is this solved @pquerner @x360andy ?

**Comment by x360andy** [comment]
yes thanks
