### ISSUE TITLE
Unable to install with Laravel 5.6

### ISSUE THREAD

**Issue by pquerner** [repat/plentymarkets-rest-client#5]
Because of https://github.com/laravel/framework/blob/5.6/composer.json#L26

**Comment by repat** [comment]
Did you try out the pull request or guessing it'd work ;)?

**Comment by repat** [comment]
While you're at it, you don't happen to use PHP 7.2 so we can fix #4 too?

**Comment by pquerner** [comment]
Uhm I just used ```composer install``` to verify. No code has been written yet to actually use that. But I guessed this little dependency update wont hurt the normal code base, as the original "carbon" doesnt look so active anymore.

And yes, I am planning to use PHP7.2.
